In [10]:
import pandas as pd
import numpy as np
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [11]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)

In [12]:
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [13]:
# Converting string labels into numbers
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print ("Temp:",temp_encoded)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [14]:
print("Play:",label)

Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [15]:
#Combinig weather and temp into single listof tuples
#features=np.array(zip(weather_encoded,temp_encoded))
features=np.vstack((weather_encoded,temp_encoded))
#list(features)
list(features)

[array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64),
 array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)]

In [16]:
list(label)

[0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]

In [17]:
label.size

14

In [22]:
a=np.array(list(zip(weather_encoded,temp_encoded)))
a

array([[2, 1],
       [2, 1],
       [0, 1],
       [1, 2],
       [1, 0],
       [1, 0],
       [0, 0],
       [2, 2],
       [2, 0],
       [1, 2],
       [2, 2],
       [0, 2],
       [0, 1],
       [1, 2]], dtype=int64)

In [23]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
#Create a Gaussian Classifier/ using laplace correlation as 1
model = GaussianNB(var_smoothing=1)
# Train the model using the training sets
model.fit(a,label)

GaussianNB(var_smoothing=1)

In [28]:
#Predict Output
predicted= model.predict([[2,1]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [0]


In [42]:
def Naive_Bayes(a):
    # Step 1: Calculate Prior Probability
    y_unique = a..unique()
    prior_probability = np.zeros(len(a.y.unique()))
    for i in range(0,len(y_unique)):
        prior_probability[i]=sum(a['y']==y_unique[i])/len(a['y'])
    
    # Step 2: Calculate Conditional Probability
    conditional_probability = {}
    for i in range(1,a.shape[1]):
        x_unique = list(set(a['x'+str(i)]))
        x_conditional_probability = np.zeros((len(a.y.unique()),len(set(a['x'+str(i)]))))
        for j in range(0,len(y_unique)):
            for k in range(0,len(x_unique)):
                x_conditional_probability[j,k]=a.loc[(a['x'+str(i)]==x_unique[k])&(a['y']==y_unique[j]),].shape[0]/sum(a['y']==y_unique[j])
    
        x_conditional_probability = pd.aFrame(x_conditional_probability,columns=x_unique,index=y_unique)   
        conditional_probability['x'+str(i)] = x_conditional_probability       
    
    return prior_probability,conditional_probability
    
 
prior_probability,conditional_probability = Naive_Bayes(a)

SyntaxError: invalid syntax (437195396.py, line 3)

In [29]:
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
wine = datasets.load_wine()

In [31]:
# print the names of the 13 features
print ("Features: ", wine.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print ("Labels: ", wine.target_names)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']


In [32]:
# print data(feature)shape
wine.data.shape

(178, 13)

In [34]:
# print the wine data features (top 5 records)
print (wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [35]:
# print the wine labels (0:Class_0, 1:class_2, 2:class_2)
print (wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [38]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3,random_state=109) # 70% training and 30% test

In [39]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [40]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9074074074074074
